// fluxo de dados

/// COISA MAIS AVANÇADA, REPLICAR AQUI O VÍDEO SEM ENTENDER MUITO BEM
/// BUSCAR OUTRO CONTEÚDO 
/// FUNÇÃO STREAM - FLUXO DE DADOS, MELHOR USADO COM O PACOTE RXDART 
/// 
/// SÓ PRA SABER O QUE ERA - MANIPULAÇÃO DE DADOS CADASTRADOS EM UM FORMULÁRIO POR EXEMPLO
/// 